(specifications->manifest
 (list "alacritty"
       "aspell"
       "bash"
       "direnv"
       "emacs"
       "fontconfig"
       "font-hack"
       "git"
       "glibc-locales"
       "guile"
       "guix"
       "libcanberra"	 ; check if this is needed for emacs.
       "pass-git-helper"
       "password-store"
       "python-beautysh" ; from my packages. Possibly try to push to guix channel.
       "qutebrowser"
       "rclone"
       "redshift"
       "restic"
       "ripgrep"
       "sbcl"
       "shellcheck"
       "stow"
       "stumpwm-with-slynk"
       "tmux"
       "xlsfonts"
       "zsh"))
